// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnzhjrrlqdalchjcgojx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuemhqcnJscWRhbGNoamNnb2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1ODI5ODIsImV4cCI6MjA2NjE1ODk4Mn0.FKf1EYAZGuflRmqoFE3agA7AdSWtJPHbZ7MH6DnjvuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);